---
- hosts: web
  gather_facts: no
  become: yes
  pre_tasks:
#    - raw: "test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal software-properties-common python-pip)"
    - setup:
  tasks:
    - debug: msg="privetiki"
  roles:
    - basesystem
    - { name: 'nginx', tags: 'nginx'}
    - { name: 'uwsgi', tags: 'uwsgi'}

- hosts: lb
  gather_facts: yes
  become: yes
  roles:
    - { name: 'haproxy', tags: 'haproxy'}
