---
- hosts: web
  gather_facts: no
  become: yes
  pre_tasks:
    - setup:
  roles:
    - basesystem
    - { name: 'nginx', tags: 'nginx'}
    - { name: 'uwsgi', tags: 'uwsgi'}

- hosts: lb
  gather_facts: yes
  become: yes
  roles:
    - haproxy
  tags: haproxy

# deploy part
- hosts: web
  become: yes
  tasks:
    - synchronize:
        src: src/
        dest: "{{ web__project_directory }}/app"
    - systemd: name=app state=restarted
  tags: deploy
